### ISSUE TITLE
Build failures when following book instructions

### ISSUE THREAD

**Issue by aggieben** [Zaid-Ajaj/elmish-getting-started#2]
I've started going through _The Elmish Book_ (which I've really been enjoying, btw - it's the perfect pace and breakdown of detail to help deal with the complexity of shipping frontend apps), but ran into problems in the [Counter with Elmish](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/elm/counter) section.

Following the instructions results in the following build error:
![image](https://user-images.githubusercontent.com/1321/78262768-a8a5b480-74c6-11ea-94b8-7ed11faa16fa.png)

Aside: You may note that I was using Yarn rather than NPM, but I did try this with NPM just to make sure that wasn't a key difference and got the same result.

I tried running the `dotnet msbuild` command just as it appears in the error output, and got this:

![image](https://user-images.githubusercontent.com/1321/78263110-249ffc80-74c7-11ea-98e7-4f973f28266d.png)

for the search engines: 
```
Fable.Elmish.fsproj(16,3): error MSB4019: The imported project "D:\Users\ben\proj\learning\elmish\elmish-gett
ing-started\.fable\.paket\Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration "..\.paket\Paket.Restore.targets" is correct, and that the file exists on
disk.
```

It appears to me that the underlying problem is that the projects in `.fable` depend on a paket setup that doesn't exist in this repository.  As of yet I'm not even sure how the `.fable` directory and its contents were created, and I'm not sure what to do to proceed.

**Comment by Zaid-Ajaj** [comment]
Hello there @aggieben, I am glad you are enjoying the book :smile: 

This error is weird, I haven't seen it before to be honest 🤔 it seems that it is trying to compile all projects in `.fable` and cannot find their paket dependencies but these are just build artifacts artifacts when compiling a Fable project and you should ignore them. 

Maybe it has to do with the fact that you are using latest of all latest dotnet. Can you please try building the project only using dotnet. i.e. running this:
```bash
cd elmish-getting-started
cd src
dotnet build
```

**Comment by aggieben** [comment]
@Zaid-Ajaj  That worked:

![image](https://user-images.githubusercontent.com/1321/78301012-13bead80-74fe-11ea-8001-02e1fe7b659a.png)

**Comment by aggieben** [comment]
So what's going on during the build?  That's the part that's a bit magical to me.  Does the fable-loader create the `.fable` directory and copy stuff from the nuget packages?  If so, how did this ever work?  Just from glancing over at elmish/react, it seems that these projects have been this way for a long time.

**Comment by Zaid-Ajaj** [comment]
It is actually `fable-compiler` that copies the *source files* of the nuget packages (see [Fable Packages](https://zaid-ajaj.github.io/the-elmish-book/#/chapters/fable/fable-packages)). Content from both the direct dependencies and the transitive dependencies are copied into `.fable` and are topologically sorted to allow Fable to compile the entire application along with its dependencies. 

> If so, how did this ever work?

It works like a charm! Well usually at least. I am sorry about this experience, it must be really frustrating. I am sure this must be some weird machine-specific error because this project structure is as standard as it can be using all defaults. It looks like the command `dotnet msbuild` is taking these subprojects from `.fable` into the build process even they are just build artifacts of Fable itself. 

Try the following things please:
 - Delete `.fable`, `obj`, `bin` and try `yarn build` again
 - Running `yarn build` from the usual `cmd` (opening it using admin privileges)  because it might that the terminal is doing weird CWD overwriting
 
Let me know how it goes, I hope it works. if it doesn't please consider filing an issue of Fables' repo so that we can track this problem and find the solution for it

**Comment by aggieben** [comment]
@Zaid-Ajaj It fails in the same way, unfortunately:
![image](https://user-images.githubusercontent.com/1321/78306266-93517a00-7508-11ea-93b7-d044c99efe31.png)

**Comment by aggieben** [comment]
@Zaid-Ajaj you maybe have seen my last update over on the fable-compiler/Fable#2006 issue, but it came down to a Windows junction making webpack unhappy somehow.  I'm back to enjoying your fabulous content.  Thanks!
